name: Apec

on:
  workflow_dispatch:

jobs:
  download-and-compare:
    name: Download and compare JAR files
    runs-on: ubuntu-latest
    steps:
      - name: "Download Wyvest's copy"
        run: |
          wget https://github.com/Wyvest/Apec/releases/download/1.12.4/Apec-1.8.9-forge-1.12.4.jar
          wget https://github.com/Wyvest/Apec/releases/download/1.12.4/Apec-1.8.9-forge-1.12.4-dev.jar
          mv Apec-1.8.9-forge-1.12.4.jar Wyvest-Apec-1.8.9-forge-1.12.4.jar
          mv Apec-1.8.9-forge-1.12.4-dev.jar Wyvest-Apec-1.8.9-forge-1.12.4-dev.jar
      - name: Supply hashes & hash info
        run: |
          sha256sum BananaFructa-Apec-1.8.9-forge-1.12.4-dev.jar
          sha256sum Wyvest-Apec-1.8.9-forge-1.12.4-dev.jar
